# Site settings
title: DY Blog
SEOTitle: 邓琰的博客 | DY Blog
header-img: img/post-bg-desk.jpg
email: dengyan1919@gmail.com
description: "description here."
keyword: "keyword, DY Blog, ..."
url: "http://eyedeng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/eyedeng/eyedeng.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "about here"
sidebar-avatar: /img/fhp.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username:    eyedeng
# facebook_username:  baiying.qiu.7
jianshu_username:   c4d8d39935cf
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: c0a5d86a417d9ce175d2                            #生成的clientID
  clientSecret: 159a37eb46f92186eb6cb9270ee71f5a8e05b941    #生成的clientSecret
  repo: eyedeng.github.io    #仓库名称
  owner: eyedeng    #github用户名
  admin: eyedeng
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 40b360fefba36de1b4932862bc07cdd1
          
# Google Analytics
ga_track_id: 'UA-143167247-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/weixin_43958765"
    },{
        title: "coursera",
        href: "https://www.coursera.org"
    },{
        title: "udcity",
        href: "https://cn.udacity.com"
    },{
        title: "edx",
        href: "https://www.edx.org"
    },{
        title: "stanford",
        href: "https://lagunita.stanford.edu"
    }
]
